# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

encode58_string <- function(input, alphabet) {
    .Call(`_shortuuid_encode58_string`, input, alphabet)
}

encode58_int <- function(input, alphabet) {
    .Call(`_shortuuid_encode58_int`, input, alphabet)
}

uuid_to_base58_cpp <- function(uuid_str, alphabet) {
    .Call(`_shortuuid_uuid_to_base58_cpp`, uuid_str, alphabet)
}

bytes_to_hex <- function(bytes) {
    .Call(`_shortuuid_bytes_to_hex`, bytes)
}

base58_to_uuid_cpp <- function(base58, alphabet) {
    .Call(`_shortuuid_base58_to_uuid_cpp`, base58, alphabet)
}

uuid_v4 <- function() {
    .Call(`_shortuuid_uuid_v4`)
}

